/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.lists.types;

import com.courier.api.core.ObjectMappers;
import com.courier.api.resources.commons.types.RecipientPreferences;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ListPutParams.Builder.class)
public final class ListPutParams {
    private final String name;

    private final Optional<RecipientPreferences> preferences;

    private final Map<String, Object> additionalProperties;

    private ListPutParams(
            String name, Optional<RecipientPreferences> preferences, Map<String, Object> additionalProperties) {
        this.name = name;
        this.preferences = preferences;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("preferences")
    public Optional<RecipientPreferences> getPreferences() {
        return preferences;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListPutParams && equalTo((ListPutParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListPutParams other) {
        return name.equals(other.name) && preferences.equals(other.preferences);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.name, this.preferences);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        _FinalStage name(String name);

        Builder from(ListPutParams other);
    }

    public interface _FinalStage {
        ListPutParams build();

        _FinalStage preferences(Optional<RecipientPreferences> preferences);

        _FinalStage preferences(RecipientPreferences preferences);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, _FinalStage {
        private String name;

        private Optional<RecipientPreferences> preferences = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ListPutParams other) {
            name(other.getName());
            preferences(other.getPreferences());
            return this;
        }

        @Override
        @JsonSetter("name")
        public _FinalStage name(String name) {
            this.name = name;
            return this;
        }

        @Override
        public _FinalStage preferences(RecipientPreferences preferences) {
            this.preferences = Optional.of(preferences);
            return this;
        }

        @Override
        @JsonSetter(value = "preferences", nulls = Nulls.SKIP)
        public _FinalStage preferences(Optional<RecipientPreferences> preferences) {
            this.preferences = preferences;
            return this;
        }

        @Override
        public ListPutParams build() {
            return new ListPutParams(name, preferences, additionalProperties);
        }
    }
}
