/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.lists.requests;

import com.courier.api.core.ObjectMappers;
import com.courier.api.resources.commons.types.RecipientPreferences;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SubscribeUserToListRequest.Builder.class)
public final class SubscribeUserToListRequest {
    private final Optional<RecipientPreferences> preferences;

    private final Map<String, Object> additionalProperties;

    private SubscribeUserToListRequest(
            Optional<RecipientPreferences> preferences, Map<String, Object> additionalProperties) {
        this.preferences = preferences;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("preferences")
    public Optional<RecipientPreferences> getPreferences() {
        return preferences;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SubscribeUserToListRequest && equalTo((SubscribeUserToListRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SubscribeUserToListRequest other) {
        return preferences.equals(other.preferences);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.preferences);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<RecipientPreferences> preferences = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SubscribeUserToListRequest other) {
            preferences(other.getPreferences());
            return this;
        }

        @JsonSetter(value = "preferences", nulls = Nulls.SKIP)
        public Builder preferences(Optional<RecipientPreferences> preferences) {
            this.preferences = preferences;
            return this;
        }

        public Builder preferences(RecipientPreferences preferences) {
            this.preferences = Optional.ofNullable(preferences);
            return this;
        }

        public SubscribeUserToListRequest build() {
            return new SubscribeUserToListRequest(preferences, additionalProperties);
        }
    }
}
