/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.auditevents.types;

import com.courier.api.core.ObjectMappers;
import com.courier.api.resources.commons.types.Paging;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = ListAuditEventsResponse.Builder.class)
public final class ListAuditEventsResponse {
    private final Paging paging;

    private final List<AuditEvent> results;

    private final Map<String, Object> additionalProperties;

    private ListAuditEventsResponse(Paging paging, List<AuditEvent> results, Map<String, Object> additionalProperties) {
        this.paging = paging;
        this.results = results;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("paging")
    public Paging getPaging() {
        return paging;
    }

    @JsonProperty("results")
    public List<AuditEvent> getResults() {
        return results;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListAuditEventsResponse && equalTo((ListAuditEventsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListAuditEventsResponse other) {
        return paging.equals(other.paging) && results.equals(other.results);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.paging, this.results);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PagingStage builder() {
        return new Builder();
    }

    public interface PagingStage {
        _FinalStage paging(Paging paging);

        Builder from(ListAuditEventsResponse other);
    }

    public interface _FinalStage {
        ListAuditEventsResponse build();

        _FinalStage results(List<AuditEvent> results);

        _FinalStage addResults(AuditEvent results);

        _FinalStage addAllResults(List<AuditEvent> results);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PagingStage, _FinalStage {
        private Paging paging;

        private List<AuditEvent> results = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ListAuditEventsResponse other) {
            paging(other.getPaging());
            results(other.getResults());
            return this;
        }

        @Override
        @JsonSetter("paging")
        public _FinalStage paging(Paging paging) {
            this.paging = paging;
            return this;
        }

        @Override
        public _FinalStage addAllResults(List<AuditEvent> results) {
            this.results.addAll(results);
            return this;
        }

        @Override
        public _FinalStage addResults(AuditEvent results) {
            this.results.add(results);
            return this;
        }

        @Override
        @JsonSetter(value = "results", nulls = Nulls.SKIP)
        public _FinalStage results(List<AuditEvent> results) {
            this.results.clear();
            this.results.addAll(results);
            return this;
        }

        @Override
        public ListAuditEventsResponse build() {
            return new ListAuditEventsResponse(paging, results, additionalProperties);
        }
    }
}
