/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.send.types;

import com.courier.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BaseMessageSendTo.Builder.class)
public final class BaseMessageSendTo implements IBaseMessageSendTo {
    private final Optional<MessageRecipient> to;

    private final Map<String, Object> additionalProperties;

    private BaseMessageSendTo(Optional<MessageRecipient> to, Map<String, Object> additionalProperties) {
        this.to = to;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The recipient or a list of recipients of the message
     */
    @JsonProperty("to")
    @java.lang.Override
    public Optional<MessageRecipient> getTo() {
        return to;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BaseMessageSendTo && equalTo((BaseMessageSendTo) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BaseMessageSendTo other) {
        return to.equals(other.to);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.to);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<MessageRecipient> to = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BaseMessageSendTo other) {
            to(other.getTo());
            return this;
        }

        /**
         * <p>The recipient or a list of recipients of the message</p>
         */
        @JsonSetter(value = "to", nulls = Nulls.SKIP)
        public Builder to(Optional<MessageRecipient> to) {
            this.to = to;
            return this;
        }

        public Builder to(MessageRecipient to) {
            this.to = Optional.ofNullable(to);
            return this;
        }

        public BaseMessageSendTo build() {
            return new BaseMessageSendTo(to, additionalProperties);
        }
    }
}
