/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.send.types;

import java.util.Map;
import java.util.Optional;

public interface IBaseMessage {
    Optional<Map<String, Object>> getData();

    Optional<String> getBrandId();

    Optional<Map<String, Channel>> getChannels();

    Optional<MessageContext> getContext();

    Optional<MessageMetadata> getMetadata();

    Optional<MessagePreferences> getPreferences();

    Optional<Map<String, MessageProvidersType>> getProviders();

    Optional<Routing> getRouting();

    Optional<Timeout> getTimeout();

    Optional<Delay> getDelay();

    Optional<Expiry> getExpiry();
}
