/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.send.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Override {
    MESSAGE_CHANNEL_EMAIL_OVERRIDE("MessageChannelEmailOverride"),

    MESSAGE_CHANNEL_PUSH_OVERRIDE("MessageChannelPushOverride");

    private final String value;

    Override(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
