/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.send.types;

import com.courier.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = RoutingChannel.Deserializer.class)
public final class RoutingChannel {
    private final Object value;

    private final int type;

    private RoutingChannel(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((RoutingStrategyChannel) this.value);
        } else if (this.type == 1) {
            return visitor.visit((RoutingStrategyProvider) this.value);
        } else if (this.type == 2) {
            return visitor.visit((String) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RoutingChannel && equalTo((RoutingChannel) other);
    }

    private boolean equalTo(RoutingChannel other) {
        return value.equals(other.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @Override
    public String toString() {
        return this.value.toString();
    }

    public static RoutingChannel of(RoutingStrategyChannel value) {
        return new RoutingChannel(value, 0);
    }

    public static RoutingChannel of(RoutingStrategyProvider value) {
        return new RoutingChannel(value, 1);
    }

    public static RoutingChannel of(String value) {
        return new RoutingChannel(value, 2);
    }

    public interface Visitor<T> {
        T visit(RoutingStrategyChannel value);

        T visit(RoutingStrategyProvider value);

        T visit(String value);
    }

    static final class Deserializer extends StdDeserializer<RoutingChannel> {
        Deserializer() {
            super(RoutingChannel.class);
        }

        @Override
        public RoutingChannel deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, RoutingStrategyChannel.class));
            } catch (IllegalArgumentException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, RoutingStrategyProvider.class));
            } catch (IllegalArgumentException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
            } catch (IllegalArgumentException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
