/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.send.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TextStyle {
    TEXT("text"),

    H_1("h1"),

    H_2("h2"),

    SUBTEXT("subtext");

    private final String value;

    TextStyle(String value) {
        this.value = value;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
