/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.automations.types;

import com.courier.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AutomationUpdateProfileStep.Builder.class)
public final class AutomationUpdateProfileStep {
    private final String recipientId;

    private final Object profile;

    private final MergeAlgorithm merge;

    private final Map<String, Object> additionalProperties;

    private AutomationUpdateProfileStep(
            String recipientId, Object profile, MergeAlgorithm merge, Map<String, Object> additionalProperties) {
        this.recipientId = recipientId;
        this.profile = profile;
        this.merge = merge;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("action")
    public String getAction() {
        return "update-profile";
    }

    @JsonProperty("recipient_id")
    public String getRecipientId() {
        return recipientId;
    }

    @JsonProperty("profile")
    public Object getProfile() {
        return profile;
    }

    @JsonProperty("merge")
    public MergeAlgorithm getMerge() {
        return merge;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AutomationUpdateProfileStep && equalTo((AutomationUpdateProfileStep) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AutomationUpdateProfileStep other) {
        return recipientId.equals(other.recipientId) && profile.equals(other.profile) && merge.equals(other.merge);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.recipientId, this.profile, this.merge);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RecipientIdStage builder() {
        return new Builder();
    }

    public interface RecipientIdStage {
        ProfileStage recipientId(@NotNull String recipientId);

        Builder from(AutomationUpdateProfileStep other);
    }

    public interface ProfileStage {
        MergeStage profile(Object profile);
    }

    public interface MergeStage {
        _FinalStage merge(@NotNull MergeAlgorithm merge);
    }

    public interface _FinalStage {
        AutomationUpdateProfileStep build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RecipientIdStage, ProfileStage, MergeStage, _FinalStage {
        private String recipientId;

        private Object profile;

        private MergeAlgorithm merge;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AutomationUpdateProfileStep other) {
            recipientId(other.getRecipientId());
            profile(other.getProfile());
            merge(other.getMerge());
            return this;
        }

        @java.lang.Override
        @JsonSetter("recipient_id")
        public ProfileStage recipientId(@NotNull String recipientId) {
            this.recipientId = Objects.requireNonNull(recipientId, "recipientId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("profile")
        public MergeStage profile(Object profile) {
            this.profile = profile;
            return this;
        }

        @java.lang.Override
        @JsonSetter("merge")
        public _FinalStage merge(@NotNull MergeAlgorithm merge) {
            this.merge = Objects.requireNonNull(merge, "merge must not be null");
            return this;
        }

        @java.lang.Override
        public AutomationUpdateProfileStep build() {
            return new AutomationUpdateProfileStep(recipientId, profile, merge, additionalProperties);
        }
    }
}
