/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.profiles.types;

import com.courier.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SendToSlackChannel.Builder.class)
public final class SendToSlackChannel implements ISlackBaseProperties {
    private final String accessToken;

    private final String channel;

    private final Map<String, Object> additionalProperties;

    private SendToSlackChannel(String accessToken, String channel, Map<String, Object> additionalProperties) {
        this.accessToken = accessToken;
        this.channel = channel;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("access_token")
    @java.lang.Override
    public String getAccessToken() {
        return accessToken;
    }

    @JsonProperty("channel")
    public String getChannel() {
        return channel;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SendToSlackChannel && equalTo((SendToSlackChannel) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SendToSlackChannel other) {
        return accessToken.equals(other.accessToken) && channel.equals(other.channel);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.accessToken, this.channel);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AccessTokenStage builder() {
        return new Builder();
    }

    public interface AccessTokenStage {
        ChannelStage accessToken(@NotNull String accessToken);

        Builder from(SendToSlackChannel other);
    }

    public interface ChannelStage {
        _FinalStage channel(@NotNull String channel);
    }

    public interface _FinalStage {
        SendToSlackChannel build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AccessTokenStage, ChannelStage, _FinalStage {
        private String accessToken;

        private String channel;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SendToSlackChannel other) {
            accessToken(other.getAccessToken());
            channel(other.getChannel());
            return this;
        }

        @java.lang.Override
        @JsonSetter("access_token")
        public ChannelStage accessToken(@NotNull String accessToken) {
            this.accessToken = Objects.requireNonNull(accessToken, "accessToken must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("channel")
        public _FinalStage channel(@NotNull String channel) {
            this.channel = Objects.requireNonNull(channel, "channel must not be null");
            return this;
        }

        @java.lang.Override
        public SendToSlackChannel build() {
            return new SendToSlackChannel(accessToken, channel, additionalProperties);
        }
    }
}
