/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.profiles.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SnoozeRuleType {
    SNOOZE("snooze");

    private final String value;

    SnoozeRuleType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
