/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.profiles.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum WebhookAuthMode {
    NONE("none"),

    BASIC("basic"),

    BEARER("bearer");

    private final String value;

    WebhookAuthMode(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
