/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.users.tenants.types;

import com.courier.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = UserTenantAssociation.Builder.class)
public final class UserTenantAssociation {
    private final String tenantId;

    private final Map<String, Object> profile;

    private final Map<String, Object> additionalProperties;

    private UserTenantAssociation(
            String tenantId, Map<String, Object> profile, Map<String, Object> additionalProperties) {
        this.tenantId = tenantId;
        this.profile = profile;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Tenant ID the user association is tied to.
     */
    @JsonProperty("tenant_id")
    public String getTenantId() {
        return tenantId;
    }

    @JsonProperty("profile")
    public Map<String, Object> getProfile() {
        return profile;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserTenantAssociation && equalTo((UserTenantAssociation) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserTenantAssociation other) {
        return tenantId.equals(other.tenantId) && profile.equals(other.profile);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.tenantId, this.profile);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TenantIdStage builder() {
        return new Builder();
    }

    public interface TenantIdStage {
        _FinalStage tenantId(String tenantId);

        Builder from(UserTenantAssociation other);
    }

    public interface _FinalStage {
        UserTenantAssociation build();

        _FinalStage profile(Map<String, Object> profile);

        _FinalStage putAllProfile(Map<String, Object> profile);

        _FinalStage profile(String key, Object value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TenantIdStage, _FinalStage {
        private String tenantId;

        private Map<String, Object> profile = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(UserTenantAssociation other) {
            tenantId(other.getTenantId());
            profile(other.getProfile());
            return this;
        }

        /**
         * <p>Tenant ID the user association is tied to.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("tenant_id")
        public _FinalStage tenantId(String tenantId) {
            this.tenantId = tenantId;
            return this;
        }

        @Override
        public _FinalStage profile(String key, Object value) {
            this.profile.put(key, value);
            return this;
        }

        @Override
        public _FinalStage putAllProfile(Map<String, Object> profile) {
            this.profile.putAll(profile);
            return this;
        }

        @Override
        @JsonSetter(value = "profile", nulls = Nulls.SKIP)
        public _FinalStage profile(Map<String, Object> profile) {
            this.profile.clear();
            this.profile.putAll(profile);
            return this;
        }

        @Override
        public UserTenantAssociation build() {
            return new UserTenantAssociation(tenantId, profile, additionalProperties);
        }
    }
}
