/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.lists;

import com.courier.api.core.ClientOptions;
import com.courier.api.core.IdempotentRequestOptions;
import com.courier.api.core.RequestOptions;
import com.courier.api.resources.lists.requests.AddSubscribersToList;
import com.courier.api.resources.lists.requests.GetAllListsRequest;
import com.courier.api.resources.lists.requests.GetSubscriptionForListRequest;
import com.courier.api.resources.lists.requests.RestoreListRequest;
import com.courier.api.resources.lists.requests.SubscribeUserToListRequest;
import com.courier.api.resources.lists.requests.SubscribeUsersToListRequest;
import com.courier.api.resources.lists.types.List;
import com.courier.api.resources.lists.types.ListGetAllResponse;
import com.courier.api.resources.lists.types.ListGetSubscriptionsResponse;
import com.courier.api.resources.lists.types.ListPutParams;
import java.util.concurrent.CompletableFuture;

public class AsyncListsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawListsClient rawClient;

    public AsyncListsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawListsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawListsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns all of the lists, with the ability to filter based on a pattern.
     */
    public CompletableFuture<ListGetAllResponse> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Returns all of the lists, with the ability to filter based on a pattern.
     */
    public CompletableFuture<ListGetAllResponse> list(GetAllListsRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Returns all of the lists, with the ability to filter based on a pattern.
     */
    public CompletableFuture<ListGetAllResponse> list(GetAllListsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a list based on the list ID provided.
     */
    public CompletableFuture<List> get(String listId) {
        return this.rawClient.get(listId).thenApply(response -> response.body());
    }

    /**
     * Returns a list based on the list ID provided.
     */
    public CompletableFuture<List> get(String listId, RequestOptions requestOptions) {
        return this.rawClient.get(listId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create or replace an existing list with the supplied values.
     */
    public CompletableFuture<Void> update(String listId, ListPutParams request) {
        return this.rawClient.update(listId, request).thenApply(response -> response.body());
    }

    /**
     * Create or replace an existing list with the supplied values.
     */
    public CompletableFuture<Void> update(String listId, ListPutParams request, RequestOptions requestOptions) {
        return this.rawClient.update(listId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete a list by list ID.
     */
    public CompletableFuture<Void> delete(String listId) {
        return this.rawClient.delete(listId).thenApply(response -> response.body());
    }

    /**
     * Delete a list by list ID.
     */
    public CompletableFuture<Void> delete(String listId, RequestOptions requestOptions) {
        return this.rawClient.delete(listId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Restore a previously deleted list.
     */
    public CompletableFuture<Void> restore(String listId) {
        return this.rawClient.restore(listId).thenApply(response -> response.body());
    }

    /**
     * Restore a previously deleted list.
     */
    public CompletableFuture<Void> restore(String listId, RestoreListRequest request) {
        return this.rawClient.restore(listId, request).thenApply(response -> response.body());
    }

    /**
     * Restore a previously deleted list.
     */
    public CompletableFuture<Void> restore(String listId, RestoreListRequest request, RequestOptions requestOptions) {
        return this.rawClient.restore(listId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get the list's subscriptions.
     */
    public CompletableFuture<ListGetSubscriptionsResponse> getSubscribers(String listId) {
        return this.rawClient.getSubscribers(listId).thenApply(response -> response.body());
    }

    /**
     * Get the list's subscriptions.
     */
    public CompletableFuture<ListGetSubscriptionsResponse> getSubscribers(
            String listId, GetSubscriptionForListRequest request) {
        return this.rawClient.getSubscribers(listId, request).thenApply(response -> response.body());
    }

    /**
     * Get the list's subscriptions.
     */
    public CompletableFuture<ListGetSubscriptionsResponse> getSubscribers(
            String listId, GetSubscriptionForListRequest request, RequestOptions requestOptions) {
        return this.rawClient.getSubscribers(listId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Subscribes the users to the list, overwriting existing subscriptions. If the list does not exist, it will be automatically created.
     */
    public CompletableFuture<Void> updateSubscribers(String listId, SubscribeUsersToListRequest request) {
        return this.rawClient.updateSubscribers(listId, request).thenApply(response -> response.body());
    }

    /**
     * Subscribes the users to the list, overwriting existing subscriptions. If the list does not exist, it will be automatically created.
     */
    public CompletableFuture<Void> updateSubscribers(
            String listId, SubscribeUsersToListRequest request, RequestOptions requestOptions) {
        return this.rawClient.updateSubscribers(listId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Subscribes additional users to the list, without modifying existing subscriptions. If the list does not exist, it will be automatically created.
     */
    public CompletableFuture<Void> addSubscribers(String listId, AddSubscribersToList request) {
        return this.rawClient.addSubscribers(listId, request).thenApply(response -> response.body());
    }

    /**
     * Subscribes additional users to the list, without modifying existing subscriptions. If the list does not exist, it will be automatically created.
     */
    public CompletableFuture<Void> addSubscribers(
            String listId, AddSubscribersToList request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.addSubscribers(listId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Subscribe a user to an existing list (note: if the List does not exist, it will be automatically created).
     */
    public CompletableFuture<Void> subscribe(String listId, String userId) {
        return this.rawClient.subscribe(listId, userId).thenApply(response -> response.body());
    }

    /**
     * Subscribe a user to an existing list (note: if the List does not exist, it will be automatically created).
     */
    public CompletableFuture<Void> subscribe(String listId, String userId, SubscribeUserToListRequest request) {
        return this.rawClient.subscribe(listId, userId, request).thenApply(response -> response.body());
    }

    /**
     * Subscribe a user to an existing list (note: if the List does not exist, it will be automatically created).
     */
    public CompletableFuture<Void> subscribe(
            String listId, String userId, SubscribeUserToListRequest request, RequestOptions requestOptions) {
        return this.rawClient.subscribe(listId, userId, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete a subscription to a list by list ID and user ID.
     */
    public CompletableFuture<Void> unsubscribe(String listId, String userId) {
        return this.rawClient.unsubscribe(listId, userId).thenApply(response -> response.body());
    }

    /**
     * Delete a subscription to a list by list ID and user ID.
     */
    public CompletableFuture<Void> unsubscribe(String listId, String userId, RequestOptions requestOptions) {
        return this.rawClient.unsubscribe(listId, userId, requestOptions).thenApply(response -> response.body());
    }
}
