// File generated from our OpenAPI spec by Stainless.

package com.courier.api.models.brands

import com.courier.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BrandTest {

    @Test
    fun create() {
        val brand =
            Brand.builder()
                .id("id")
                .created(0L)
                .name("name")
                .updated(0L)
                .published(0L)
                .settings(
                    BrandSettings.builder()
                        .colors(
                            BrandSettings.Colors.builder()
                                .primary("primary")
                                .secondary("secondary")
                                .build()
                        )
                        .email(
                            BrandSettings.Email.builder()
                                .footer(
                                    BrandSettings.Email.Footer.builder()
                                        .content("content")
                                        .inheritDefault(true)
                                        .build()
                                )
                                .head(
                                    BrandSettings.Email.Head.builder()
                                        .inheritDefault(true)
                                        .content("content")
                                        .build()
                                )
                                .header(
                                    BrandSettings.Email.Header.builder()
                                        .logo(
                                            BrandSettings.Email.Header.Logo.builder()
                                                .href("href")
                                                .image("image")
                                                .build()
                                        )
                                        .barColor("barColor")
                                        .inheritDefault(true)
                                        .build()
                                )
                                .templateOverride(
                                    BrandSettings.Email.TemplateOverride.builder()
                                        .enabled(true)
                                        .backgroundColor("backgroundColor")
                                        .blocksBackgroundColor("blocksBackgroundColor")
                                        .footer("footer")
                                        .head("head")
                                        .header("header")
                                        .width("width")
                                        .mjml(
                                            BrandTemplate.builder()
                                                .enabled(true)
                                                .backgroundColor("backgroundColor")
                                                .blocksBackgroundColor("blocksBackgroundColor")
                                                .footer("footer")
                                                .head("head")
                                                .header("header")
                                                .width("width")
                                                .build()
                                        )
                                        .footerBackgroundColor("footerBackgroundColor")
                                        .footerFullWidth(true)
                                        .build()
                                )
                                .build()
                        )
                        .inapp(
                            BrandSettings.Inapp.builder()
                                .colors(
                                    BrandSettings.Inapp.Colors.builder()
                                        .primary("primary")
                                        .secondary("secondary")
                                        .build()
                                )
                                .icons(
                                    BrandSettings.Inapp.Icons.builder()
                                        .bell("bell")
                                        .message("message")
                                        .build()
                                )
                                .widgetBackground(
                                    BrandSettings.Inapp.WidgetBackground.builder()
                                        .bottomColor("bottomColor")
                                        .topColor("topColor")
                                        .build()
                                )
                                .borderRadius("borderRadius")
                                .disableMessageIcon(true)
                                .fontFamily("fontFamily")
                                .placement(BrandSettings.Inapp.Placement.TOP)
                                .build()
                        )
                        .build()
                )
                .snippets(
                    BrandSnippets.builder()
                        .addItem(BrandSnippets.Item.builder().name("name").value("value").build())
                        .build()
                )
                .version("version")
                .build()

        assertThat(brand.id()).isEqualTo("id")
        assertThat(brand.created()).isEqualTo(0L)
        assertThat(brand.name()).isEqualTo("name")
        assertThat(brand.updated()).isEqualTo(0L)
        assertThat(brand.published()).contains(0L)
        assertThat(brand.settings())
            .contains(
                BrandSettings.builder()
                    .colors(
                        BrandSettings.Colors.builder()
                            .primary("primary")
                            .secondary("secondary")
                            .build()
                    )
                    .email(
                        BrandSettings.Email.builder()
                            .footer(
                                BrandSettings.Email.Footer.builder()
                                    .content("content")
                                    .inheritDefault(true)
                                    .build()
                            )
                            .head(
                                BrandSettings.Email.Head.builder()
                                    .inheritDefault(true)
                                    .content("content")
                                    .build()
                            )
                            .header(
                                BrandSettings.Email.Header.builder()
                                    .logo(
                                        BrandSettings.Email.Header.Logo.builder()
                                            .href("href")
                                            .image("image")
                                            .build()
                                    )
                                    .barColor("barColor")
                                    .inheritDefault(true)
                                    .build()
                            )
                            .templateOverride(
                                BrandSettings.Email.TemplateOverride.builder()
                                    .enabled(true)
                                    .backgroundColor("backgroundColor")
                                    .blocksBackgroundColor("blocksBackgroundColor")
                                    .footer("footer")
                                    .head("head")
                                    .header("header")
                                    .width("width")
                                    .mjml(
                                        BrandTemplate.builder()
                                            .enabled(true)
                                            .backgroundColor("backgroundColor")
                                            .blocksBackgroundColor("blocksBackgroundColor")
                                            .footer("footer")
                                            .head("head")
                                            .header("header")
                                            .width("width")
                                            .build()
                                    )
                                    .footerBackgroundColor("footerBackgroundColor")
                                    .footerFullWidth(true)
                                    .build()
                            )
                            .build()
                    )
                    .inapp(
                        BrandSettings.Inapp.builder()
                            .colors(
                                BrandSettings.Inapp.Colors.builder()
                                    .primary("primary")
                                    .secondary("secondary")
                                    .build()
                            )
                            .icons(
                                BrandSettings.Inapp.Icons.builder()
                                    .bell("bell")
                                    .message("message")
                                    .build()
                            )
                            .widgetBackground(
                                BrandSettings.Inapp.WidgetBackground.builder()
                                    .bottomColor("bottomColor")
                                    .topColor("topColor")
                                    .build()
                            )
                            .borderRadius("borderRadius")
                            .disableMessageIcon(true)
                            .fontFamily("fontFamily")
                            .placement(BrandSettings.Inapp.Placement.TOP)
                            .build()
                    )
                    .build()
            )
        assertThat(brand.snippets())
            .contains(
                BrandSnippets.builder()
                    .addItem(BrandSnippets.Item.builder().name("name").value("value").build())
                    .build()
            )
        assertThat(brand.version()).contains("version")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val brand =
            Brand.builder()
                .id("id")
                .created(0L)
                .name("name")
                .updated(0L)
                .published(0L)
                .settings(
                    BrandSettings.builder()
                        .colors(
                            BrandSettings.Colors.builder()
                                .primary("primary")
                                .secondary("secondary")
                                .build()
                        )
                        .email(
                            BrandSettings.Email.builder()
                                .footer(
                                    BrandSettings.Email.Footer.builder()
                                        .content("content")
                                        .inheritDefault(true)
                                        .build()
                                )
                                .head(
                                    BrandSettings.Email.Head.builder()
                                        .inheritDefault(true)
                                        .content("content")
                                        .build()
                                )
                                .header(
                                    BrandSettings.Email.Header.builder()
                                        .logo(
                                            BrandSettings.Email.Header.Logo.builder()
                                                .href("href")
                                                .image("image")
                                                .build()
                                        )
                                        .barColor("barColor")
                                        .inheritDefault(true)
                                        .build()
                                )
                                .templateOverride(
                                    BrandSettings.Email.TemplateOverride.builder()
                                        .enabled(true)
                                        .backgroundColor("backgroundColor")
                                        .blocksBackgroundColor("blocksBackgroundColor")
                                        .footer("footer")
                                        .head("head")
                                        .header("header")
                                        .width("width")
                                        .mjml(
                                            BrandTemplate.builder()
                                                .enabled(true)
                                                .backgroundColor("backgroundColor")
                                                .blocksBackgroundColor("blocksBackgroundColor")
                                                .footer("footer")
                                                .head("head")
                                                .header("header")
                                                .width("width")
                                                .build()
                                        )
                                        .footerBackgroundColor("footerBackgroundColor")
                                        .footerFullWidth(true)
                                        .build()
                                )
                                .build()
                        )
                        .inapp(
                            BrandSettings.Inapp.builder()
                                .colors(
                                    BrandSettings.Inapp.Colors.builder()
                                        .primary("primary")
                                        .secondary("secondary")
                                        .build()
                                )
                                .icons(
                                    BrandSettings.Inapp.Icons.builder()
                                        .bell("bell")
                                        .message("message")
                                        .build()
                                )
                                .widgetBackground(
                                    BrandSettings.Inapp.WidgetBackground.builder()
                                        .bottomColor("bottomColor")
                                        .topColor("topColor")
                                        .build()
                                )
                                .borderRadius("borderRadius")
                                .disableMessageIcon(true)
                                .fontFamily("fontFamily")
                                .placement(BrandSettings.Inapp.Placement.TOP)
                                .build()
                        )
                        .build()
                )
                .snippets(
                    BrandSnippets.builder()
                        .addItem(BrandSnippets.Item.builder().name("name").value("value").build())
                        .build()
                )
                .version("version")
                .build()

        val roundtrippedBrand =
            jsonMapper.readValue(jsonMapper.writeValueAsString(brand), jacksonTypeRef<Brand>())

        assertThat(roundtrippedBrand).isEqualTo(brand)
    }
}
