// File generated from our OpenAPI spec by Stainless.

package com.courier.api.models.brands

import com.courier.api.core.jsonMapper
import com.courier.api.models.audiences.Paging
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BrandListResponseTest {

    @Test
    fun create() {
        val brandListResponse =
            BrandListResponse.builder()
                .paging(Paging.builder().more(true).cursor("cursor").build())
                .addResult(
                    Brand.builder()
                        .id("id")
                        .created(0L)
                        .name("name")
                        .updated(0L)
                        .published(0L)
                        .settings(
                            BrandSettings.builder()
                                .colors(
                                    BrandSettings.Colors.builder()
                                        .primary("primary")
                                        .secondary("secondary")
                                        .build()
                                )
                                .email(
                                    BrandSettings.Email.builder()
                                        .footer(
                                            BrandSettings.Email.Footer.builder()
                                                .content("content")
                                                .inheritDefault(true)
                                                .build()
                                        )
                                        .head(
                                            BrandSettings.Email.Head.builder()
                                                .inheritDefault(true)
                                                .content("content")
                                                .build()
                                        )
                                        .header(
                                            BrandSettings.Email.Header.builder()
                                                .logo(
                                                    BrandSettings.Email.Header.Logo.builder()
                                                        .href("href")
                                                        .image("image")
                                                        .build()
                                                )
                                                .barColor("barColor")
                                                .inheritDefault(true)
                                                .build()
                                        )
                                        .templateOverride(
                                            BrandSettings.Email.TemplateOverride.builder()
                                                .enabled(true)
                                                .backgroundColor("backgroundColor")
                                                .blocksBackgroundColor("blocksBackgroundColor")
                                                .footer("footer")
                                                .head("head")
                                                .header("header")
                                                .width("width")
                                                .mjml(
                                                    BrandTemplate.builder()
                                                        .enabled(true)
                                                        .backgroundColor("backgroundColor")
                                                        .blocksBackgroundColor(
                                                            "blocksBackgroundColor"
                                                        )
                                                        .footer("footer")
                                                        .head("head")
                                                        .header("header")
                                                        .width("width")
                                                        .build()
                                                )
                                                .footerBackgroundColor("footerBackgroundColor")
                                                .footerFullWidth(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .inapp(
                                    BrandSettings.Inapp.builder()
                                        .colors(
                                            BrandSettings.Inapp.Colors.builder()
                                                .primary("primary")
                                                .secondary("secondary")
                                                .build()
                                        )
                                        .icons(
                                            BrandSettings.Inapp.Icons.builder()
                                                .bell("bell")
                                                .message("message")
                                                .build()
                                        )
                                        .widgetBackground(
                                            BrandSettings.Inapp.WidgetBackground.builder()
                                                .bottomColor("bottomColor")
                                                .topColor("topColor")
                                                .build()
                                        )
                                        .borderRadius("borderRadius")
                                        .disableMessageIcon(true)
                                        .fontFamily("fontFamily")
                                        .placement(BrandSettings.Inapp.Placement.TOP)
                                        .build()
                                )
                                .build()
                        )
                        .snippets(
                            BrandSnippets.builder()
                                .addItem(
                                    BrandSnippets.Item.builder().name("name").value("value").build()
                                )
                                .build()
                        )
                        .version("version")
                        .build()
                )
                .build()

        assertThat(brandListResponse.paging())
            .isEqualTo(Paging.builder().more(true).cursor("cursor").build())
        assertThat(brandListResponse.results())
            .containsExactly(
                Brand.builder()
                    .id("id")
                    .created(0L)
                    .name("name")
                    .updated(0L)
                    .published(0L)
                    .settings(
                        BrandSettings.builder()
                            .colors(
                                BrandSettings.Colors.builder()
                                    .primary("primary")
                                    .secondary("secondary")
                                    .build()
                            )
                            .email(
                                BrandSettings.Email.builder()
                                    .footer(
                                        BrandSettings.Email.Footer.builder()
                                            .content("content")
                                            .inheritDefault(true)
                                            .build()
                                    )
                                    .head(
                                        BrandSettings.Email.Head.builder()
                                            .inheritDefault(true)
                                            .content("content")
                                            .build()
                                    )
                                    .header(
                                        BrandSettings.Email.Header.builder()
                                            .logo(
                                                BrandSettings.Email.Header.Logo.builder()
                                                    .href("href")
                                                    .image("image")
                                                    .build()
                                            )
                                            .barColor("barColor")
                                            .inheritDefault(true)
                                            .build()
                                    )
                                    .templateOverride(
                                        BrandSettings.Email.TemplateOverride.builder()
                                            .enabled(true)
                                            .backgroundColor("backgroundColor")
                                            .blocksBackgroundColor("blocksBackgroundColor")
                                            .footer("footer")
                                            .head("head")
                                            .header("header")
                                            .width("width")
                                            .mjml(
                                                BrandTemplate.builder()
                                                    .enabled(true)
                                                    .backgroundColor("backgroundColor")
                                                    .blocksBackgroundColor("blocksBackgroundColor")
                                                    .footer("footer")
                                                    .head("head")
                                                    .header("header")
                                                    .width("width")
                                                    .build()
                                            )
                                            .footerBackgroundColor("footerBackgroundColor")
                                            .footerFullWidth(true)
                                            .build()
                                    )
                                    .build()
                            )
                            .inapp(
                                BrandSettings.Inapp.builder()
                                    .colors(
                                        BrandSettings.Inapp.Colors.builder()
                                            .primary("primary")
                                            .secondary("secondary")
                                            .build()
                                    )
                                    .icons(
                                        BrandSettings.Inapp.Icons.builder()
                                            .bell("bell")
                                            .message("message")
                                            .build()
                                    )
                                    .widgetBackground(
                                        BrandSettings.Inapp.WidgetBackground.builder()
                                            .bottomColor("bottomColor")
                                            .topColor("topColor")
                                            .build()
                                    )
                                    .borderRadius("borderRadius")
                                    .disableMessageIcon(true)
                                    .fontFamily("fontFamily")
                                    .placement(BrandSettings.Inapp.Placement.TOP)
                                    .build()
                            )
                            .build()
                    )
                    .snippets(
                        BrandSnippets.builder()
                            .addItem(
                                BrandSnippets.Item.builder().name("name").value("value").build()
                            )
                            .build()
                    )
                    .version("version")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val brandListResponse =
            BrandListResponse.builder()
                .paging(Paging.builder().more(true).cursor("cursor").build())
                .addResult(
                    Brand.builder()
                        .id("id")
                        .created(0L)
                        .name("name")
                        .updated(0L)
                        .published(0L)
                        .settings(
                            BrandSettings.builder()
                                .colors(
                                    BrandSettings.Colors.builder()
                                        .primary("primary")
                                        .secondary("secondary")
                                        .build()
                                )
                                .email(
                                    BrandSettings.Email.builder()
                                        .footer(
                                            BrandSettings.Email.Footer.builder()
                                                .content("content")
                                                .inheritDefault(true)
                                                .build()
                                        )
                                        .head(
                                            BrandSettings.Email.Head.builder()
                                                .inheritDefault(true)
                                                .content("content")
                                                .build()
                                        )
                                        .header(
                                            BrandSettings.Email.Header.builder()
                                                .logo(
                                                    BrandSettings.Email.Header.Logo.builder()
                                                        .href("href")
                                                        .image("image")
                                                        .build()
                                                )
                                                .barColor("barColor")
                                                .inheritDefault(true)
                                                .build()
                                        )
                                        .templateOverride(
                                            BrandSettings.Email.TemplateOverride.builder()
                                                .enabled(true)
                                                .backgroundColor("backgroundColor")
                                                .blocksBackgroundColor("blocksBackgroundColor")
                                                .footer("footer")
                                                .head("head")
                                                .header("header")
                                                .width("width")
                                                .mjml(
                                                    BrandTemplate.builder()
                                                        .enabled(true)
                                                        .backgroundColor("backgroundColor")
                                                        .blocksBackgroundColor(
                                                            "blocksBackgroundColor"
                                                        )
                                                        .footer("footer")
                                                        .head("head")
                                                        .header("header")
                                                        .width("width")
                                                        .build()
                                                )
                                                .footerBackgroundColor("footerBackgroundColor")
                                                .footerFullWidth(true)
                                                .build()
                                        )
                                        .build()
                                )
                                .inapp(
                                    BrandSettings.Inapp.builder()
                                        .colors(
                                            BrandSettings.Inapp.Colors.builder()
                                                .primary("primary")
                                                .secondary("secondary")
                                                .build()
                                        )
                                        .icons(
                                            BrandSettings.Inapp.Icons.builder()
                                                .bell("bell")
                                                .message("message")
                                                .build()
                                        )
                                        .widgetBackground(
                                            BrandSettings.Inapp.WidgetBackground.builder()
                                                .bottomColor("bottomColor")
                                                .topColor("topColor")
                                                .build()
                                        )
                                        .borderRadius("borderRadius")
                                        .disableMessageIcon(true)
                                        .fontFamily("fontFamily")
                                        .placement(BrandSettings.Inapp.Placement.TOP)
                                        .build()
                                )
                                .build()
                        )
                        .snippets(
                            BrandSnippets.builder()
                                .addItem(
                                    BrandSnippets.Item.builder().name("name").value("value").build()
                                )
                                .build()
                        )
                        .version("version")
                        .build()
                )
                .build()

        val roundtrippedBrandListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(brandListResponse),
                jacksonTypeRef<BrandListResponse>(),
            )

        assertThat(roundtrippedBrandListResponse).isEqualTo(brandListResponse)
    }
}
