/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.bulk.types;

import com.courier.api.core.ObjectMappers;
import com.courier.api.resources.commons.types.Paging;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BulkGetJobUsersResponse.Builder.class)
public final class BulkGetJobUsersResponse {
    private final List<BulkMessageUserResponse> items;

    private final Paging paging;

    private final Map<String, Object> additionalProperties;

    private BulkGetJobUsersResponse(
            List<BulkMessageUserResponse> items, Paging paging, Map<String, Object> additionalProperties) {
        this.items = items;
        this.paging = paging;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("items")
    public List<BulkMessageUserResponse> getItems() {
        return items;
    }

    @JsonProperty("paging")
    public Paging getPaging() {
        return paging;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BulkGetJobUsersResponse && equalTo((BulkGetJobUsersResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BulkGetJobUsersResponse other) {
        return items.equals(other.items) && paging.equals(other.paging);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.items, this.paging);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PagingStage builder() {
        return new Builder();
    }

    public interface PagingStage {
        _FinalStage paging(@NotNull Paging paging);

        Builder from(BulkGetJobUsersResponse other);
    }

    public interface _FinalStage {
        BulkGetJobUsersResponse build();

        _FinalStage items(List<BulkMessageUserResponse> items);

        _FinalStage addItems(BulkMessageUserResponse items);

        _FinalStage addAllItems(List<BulkMessageUserResponse> items);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PagingStage, _FinalStage {
        private Paging paging;

        private List<BulkMessageUserResponse> items = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BulkGetJobUsersResponse other) {
            items(other.getItems());
            paging(other.getPaging());
            return this;
        }

        @java.lang.Override
        @JsonSetter("paging")
        public _FinalStage paging(@NotNull Paging paging) {
            this.paging = Objects.requireNonNull(paging, "paging must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllItems(List<BulkMessageUserResponse> items) {
            if (items != null) {
                this.items.addAll(items);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addItems(BulkMessageUserResponse items) {
            this.items.add(items);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "items", nulls = Nulls.SKIP)
        public _FinalStage items(List<BulkMessageUserResponse> items) {
            this.items.clear();
            if (items != null) {
                this.items.addAll(items);
            }
            return this;
        }

        @java.lang.Override
        public BulkGetJobUsersResponse build() {
            return new BulkGetJobUsersResponse(items, paging, additionalProperties);
        }
    }
}
