/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.bulk.types;

import com.courier.api.core.ObjectMappers;
import com.courier.api.resources.commons.types.RecipientPreferences;
import com.courier.api.resources.send.types.UserRecipient;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = BulkMessageUserResponse.Builder.class)
public final class BulkMessageUserResponse implements IInboundBulkMessageUser {
    private final Optional<RecipientPreferences> preferences;

    private final Optional<Object> profile;

    private final Optional<String> recipient;

    private final Optional<Object> data;

    private final Optional<UserRecipient> to;

    private final BulkJobUserStatus status;

    private final Optional<String> messageId;

    private final Map<String, Object> additionalProperties;

    private BulkMessageUserResponse(
            Optional<RecipientPreferences> preferences,
            Optional<Object> profile,
            Optional<String> recipient,
            Optional<Object> data,
            Optional<UserRecipient> to,
            BulkJobUserStatus status,
            Optional<String> messageId,
            Map<String, Object> additionalProperties) {
        this.preferences = preferences;
        this.profile = profile;
        this.recipient = recipient;
        this.data = data;
        this.to = to;
        this.status = status;
        this.messageId = messageId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("preferences")
    @java.lang.Override
    public Optional<RecipientPreferences> getPreferences() {
        return preferences;
    }

    @JsonProperty("profile")
    @java.lang.Override
    public Optional<Object> getProfile() {
        return profile;
    }

    @JsonProperty("recipient")
    @java.lang.Override
    public Optional<String> getRecipient() {
        return recipient;
    }

    @JsonProperty("data")
    @java.lang.Override
    public Optional<Object> getData() {
        return data;
    }

    @JsonProperty("to")
    @java.lang.Override
    public Optional<UserRecipient> getTo() {
        return to;
    }

    @JsonProperty("status")
    public BulkJobUserStatus getStatus() {
        return status;
    }

    @JsonProperty("messageId")
    public Optional<String> getMessageId() {
        return messageId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BulkMessageUserResponse && equalTo((BulkMessageUserResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BulkMessageUserResponse other) {
        return preferences.equals(other.preferences)
                && profile.equals(other.profile)
                && recipient.equals(other.recipient)
                && data.equals(other.data)
                && to.equals(other.to)
                && status.equals(other.status)
                && messageId.equals(other.messageId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.preferences, this.profile, this.recipient, this.data, this.to, this.status, this.messageId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static StatusStage builder() {
        return new Builder();
    }

    public interface StatusStage {
        _FinalStage status(BulkJobUserStatus status);

        Builder from(BulkMessageUserResponse other);
    }

    public interface _FinalStage {
        BulkMessageUserResponse build();

        _FinalStage preferences(Optional<RecipientPreferences> preferences);

        _FinalStage preferences(RecipientPreferences preferences);

        _FinalStage profile(Optional<Object> profile);

        _FinalStage profile(Object profile);

        _FinalStage recipient(Optional<String> recipient);

        _FinalStage recipient(String recipient);

        _FinalStage data(Optional<Object> data);

        _FinalStage data(Object data);

        _FinalStage to(Optional<UserRecipient> to);

        _FinalStage to(UserRecipient to);

        _FinalStage messageId(Optional<String> messageId);

        _FinalStage messageId(String messageId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements StatusStage, _FinalStage {
        private BulkJobUserStatus status;

        private Optional<String> messageId = Optional.empty();

        private Optional<UserRecipient> to = Optional.empty();

        private Optional<Object> data = Optional.empty();

        private Optional<String> recipient = Optional.empty();

        private Optional<Object> profile = Optional.empty();

        private Optional<RecipientPreferences> preferences = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BulkMessageUserResponse other) {
            preferences(other.getPreferences());
            profile(other.getProfile());
            recipient(other.getRecipient());
            data(other.getData());
            to(other.getTo());
            status(other.getStatus());
            messageId(other.getMessageId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public _FinalStage status(BulkJobUserStatus status) {
            this.status = status;
            return this;
        }

        @java.lang.Override
        public _FinalStage messageId(String messageId) {
            this.messageId = Optional.of(messageId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "messageId", nulls = Nulls.SKIP)
        public _FinalStage messageId(Optional<String> messageId) {
            this.messageId = messageId;
            return this;
        }

        @java.lang.Override
        public _FinalStage to(UserRecipient to) {
            this.to = Optional.of(to);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "to", nulls = Nulls.SKIP)
        public _FinalStage to(Optional<UserRecipient> to) {
            this.to = to;
            return this;
        }

        @java.lang.Override
        public _FinalStage data(Object data) {
            this.data = Optional.of(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(Optional<Object> data) {
            this.data = data;
            return this;
        }

        @java.lang.Override
        public _FinalStage recipient(String recipient) {
            this.recipient = Optional.of(recipient);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "recipient", nulls = Nulls.SKIP)
        public _FinalStage recipient(Optional<String> recipient) {
            this.recipient = recipient;
            return this;
        }

        @java.lang.Override
        public _FinalStage profile(Object profile) {
            this.profile = Optional.of(profile);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "profile", nulls = Nulls.SKIP)
        public _FinalStage profile(Optional<Object> profile) {
            this.profile = profile;
            return this;
        }

        @java.lang.Override
        public _FinalStage preferences(RecipientPreferences preferences) {
            this.preferences = Optional.of(preferences);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "preferences", nulls = Nulls.SKIP)
        public _FinalStage preferences(Optional<RecipientPreferences> preferences) {
            this.preferences = preferences;
            return this;
        }

        @java.lang.Override
        public BulkMessageUserResponse build() {
            return new BulkMessageUserResponse(
                    preferences, profile, recipient, data, to, status, messageId, additionalProperties);
        }
    }
}
