/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.users;

import com.courier.api.core.ClientOptions;
import com.courier.api.core.Suppliers;
import com.courier.api.resources.users.preferences.PreferencesClient;
import com.courier.api.resources.users.tenants.TenantsClient;
import com.courier.api.resources.users.tokens.TokensClient;
import java.util.function.Supplier;

public class UsersClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<PreferencesClient> preferencesClient;

    protected final Supplier<TenantsClient> tenantsClient;

    protected final Supplier<TokensClient> tokensClient;

    public UsersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.preferencesClient = Suppliers.memoize(() -> new PreferencesClient(clientOptions));
        this.tenantsClient = Suppliers.memoize(() -> new TenantsClient(clientOptions));
        this.tokensClient = Suppliers.memoize(() -> new TokensClient(clientOptions));
    }

    public PreferencesClient preferences() {
        return this.preferencesClient.get();
    }

    public TenantsClient tenants() {
        return this.tenantsClient.get();
    }

    public TokensClient tokens() {
        return this.tokensClient.get();
    }
}
