/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.commons.errors;

import com.courier.api.core.CourierApiApiError;
import com.courier.api.resources.commons.types.AlreadyExists;

public final class CourierApiAlreadyExistsError extends CourierApiApiError {
    /**
     * The body of the response that triggered the exception.
     */
    private final AlreadyExists body;

    public CourierApiAlreadyExistsError(AlreadyExists body) {
        super("AlreadyExistsError", 409, body);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public AlreadyExists body() {
        return this.body;
    }
}
