/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.commons.errors;

import com.courier.api.core.CourierApiApiError;
import com.courier.api.resources.commons.types.BadRequest;

public final class CourierApiBadRequestError extends CourierApiApiError {
    /**
     * The body of the response that triggered the exception.
     */
    private final BadRequest body;

    public CourierApiBadRequestError(BadRequest body) {
        super("BadRequestError", 400, body);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public BadRequest body() {
        return this.body;
    }
}
