/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.users.preferences;

import com.courier.api.core.ClientOptions;
import com.courier.api.core.CourierApiException;
import com.courier.api.core.CourierException;
import com.courier.api.core.CourierHttpResponse;
import com.courier.api.core.MediaTypes;
import com.courier.api.core.ObjectMappers;
import com.courier.api.core.QueryStringMapper;
import com.courier.api.core.RequestOptions;
import com.courier.api.resources.commons.errors.BadRequestError;
import com.courier.api.resources.commons.errors.NotFoundError;
import com.courier.api.resources.commons.types.BadRequest;
import com.courier.api.resources.commons.types.NotFound;
import com.courier.api.resources.users.preferences.requests.UserPreferencesParams;
import com.courier.api.resources.users.preferences.requests.UserPreferencesTopicParams;
import com.courier.api.resources.users.preferences.requests.UserPreferencesUpdateParams;
import com.courier.api.resources.users.preferences.types.UserPreferencesGetResponse;
import com.courier.api.resources.users.preferences.types.UserPreferencesListResponse;
import com.courier.api.resources.users.preferences.types.UserPreferencesUpdateResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawPreferencesClient {
    protected final ClientOptions clientOptions;

    public AsyncRawPreferencesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Fetch all user preferences.
     */
    public CompletableFuture<CourierHttpResponse<UserPreferencesListResponse>> list(String userId) {
        return list(userId, UserPreferencesParams.builder().build());
    }

    /**
     * Fetch all user preferences.
     */
    public CompletableFuture<CourierHttpResponse<UserPreferencesListResponse>> list(
            String userId, UserPreferencesParams request) {
        return list(userId, request, null);
    }

    /**
     * Fetch all user preferences.
     */
    public CompletableFuture<CourierHttpResponse<UserPreferencesListResponse>> list(
            String userId, UserPreferencesParams request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId)
                .addPathSegments("preferences");
        if (request.getTenantId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "tenant_id", request.getTenantId().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<CourierHttpResponse<UserPreferencesListResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new CourierHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBody.string(), UserPreferencesListResponse.class),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 400) {
                            future.completeExceptionally(new BadRequestError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, BadRequest.class),
                                    response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new CourierApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new CourierException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CourierException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Fetch user preferences for a specific subscription topic.
     */
    public CompletableFuture<CourierHttpResponse<UserPreferencesGetResponse>> get(String userId, String topicId) {
        return get(userId, topicId, UserPreferencesTopicParams.builder().build());
    }

    /**
     * Fetch user preferences for a specific subscription topic.
     */
    public CompletableFuture<CourierHttpResponse<UserPreferencesGetResponse>> get(
            String userId, String topicId, UserPreferencesTopicParams request) {
        return get(userId, topicId, request, null);
    }

    /**
     * Fetch user preferences for a specific subscription topic.
     */
    public CompletableFuture<CourierHttpResponse<UserPreferencesGetResponse>> get(
            String userId, String topicId, UserPreferencesTopicParams request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId)
                .addPathSegments("preferences")
                .addPathSegment(topicId);
        if (request.getTenantId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "tenant_id", request.getTenantId().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<CourierHttpResponse<UserPreferencesGetResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new CourierHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBody.string(), UserPreferencesGetResponse.class),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 404) {
                            future.completeExceptionally(new NotFoundError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, NotFound.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new CourierApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new CourierException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CourierException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Update or Create user preferences for a specific subscription topic.
     */
    public CompletableFuture<CourierHttpResponse<UserPreferencesUpdateResponse>> update(
            String userId, String topicId, UserPreferencesUpdateParams request) {
        return update(userId, topicId, request, null);
    }

    /**
     * Update or Create user preferences for a specific subscription topic.
     */
    public CompletableFuture<CourierHttpResponse<UserPreferencesUpdateResponse>> update(
            String userId, String topicId, UserPreferencesUpdateParams request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId)
                .addPathSegments("preferences")
                .addPathSegment(topicId);
        if (request.getTenantId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "tenant_id", request.getTenantId().get(), false);
        }
        Map<String, Object> properties = new HashMap<>();
        properties.put("topic", request.getTopic());
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(properties), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<CourierHttpResponse<UserPreferencesUpdateResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new CourierHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBody.string(), UserPreferencesUpdateResponse.class),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 400) {
                            future.completeExceptionally(new BadRequestError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, BadRequest.class),
                                    response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new CourierApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new CourierException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new CourierException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
