/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.notifications.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum BlockType {
    ACTION("action"),

    DIVIDER("divider"),

    IMAGE("image"),

    JSONNET("jsonnet"),

    LIST("list"),

    MARKDOWN("markdown"),

    QUOTE("quote"),

    TEMPLATE("template"),

    TEXT("text");

    private final String value;

    BlockType(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
