/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.courier.api.resources.notifications.types;

import com.courier.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = SubmissionChecksGetResponse.Builder.class)
public final class SubmissionChecksGetResponse {
    private final List<Check> checks;

    private final Map<String, Object> additionalProperties;

    private SubmissionChecksGetResponse(List<Check> checks, Map<String, Object> additionalProperties) {
        this.checks = checks;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("checks")
    public List<Check> getChecks() {
        return checks;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SubmissionChecksGetResponse && equalTo((SubmissionChecksGetResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SubmissionChecksGetResponse other) {
        return checks.equals(other.checks);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.checks);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<Check> checks = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SubmissionChecksGetResponse other) {
            checks(other.getChecks());
            return this;
        }

        @JsonSetter(value = "checks", nulls = Nulls.SKIP)
        public Builder checks(List<Check> checks) {
            this.checks.clear();
            this.checks.addAll(checks);
            return this;
        }

        public Builder addChecks(Check checks) {
            this.checks.add(checks);
            return this;
        }

        public Builder addAllChecks(List<Check> checks) {
            this.checks.addAll(checks);
            return this;
        }

        public SubmissionChecksGetResponse build() {
            return new SubmissionChecksGetResponse(checks, additionalProperties);
        }
    }
}
